# Generated by Django 6.0 on 2026-02-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=9800000000, max_length=15),
            preserve_default=False,
        ),
    ]
