# Generated by Django 6.0 on 2025-12-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
