# Generated by Django 6.0 on 2026-02-06 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0002_alter_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='RMS.category'),
            preserve_default=False,
        ),
    ]
